#!/bin/bash
set -euo pipefail

# Creates/updates the "biatec-stage-app-secret" Kubernetes Secret used by
# k8s/stage/deployment-mcp-stage.yaml and k8s/stage/deployment-oidc-stage.yaml, deliberately
# separate from production's "google-account-main-app-secret" (see docs/STAGE_ENVIRONMENT.md).
#
# Run this ONCE (and again only to rotate/update values) with a kubeconfig active that can write
# Secrets in the "biatec" namespace. This is a one-time manual step - CI never creates or reads
# this secret's contents.
#
# The self-custody AES key/IV, the provider-access-token-protection AES key/IV (BiatecOIDC's cached
# Google/Microsoft token claim - see BiatecOIDC/OIDC_INTEGRATION_GUIDE.md's "Provider access token
# caching" section), and the JWT signing key are ALWAYS freshly generated by this script - never
# copied from production - so a stage secret leak can never decrypt production self-custody files,
# decrypt a production-cached provider token, or forge a token any relying party would mistake for
# production's. Google/Microsoft OAuth
# credentials and the Redis connection string are supplied by you (env var or interactive prompt);
# it's fine to reuse production's OAuth app ClientId/ClientSecret here (same OAuth app, just with
# the stage redirect URIs already added per docs/STAGE_ENVIRONMENT.md) unless you'd rather register
# a fully separate OAuth app for stage too.
#
# Usage (any omitted variable is prompted for interactively):
#   GOOGLE_CLIENT_ID=... GOOGLE_CLIENT_SECRET=... \
#   ENTRA_TENANT_ID=common ENTRA_CLIENT_ID=... ENTRA_CLIENT_SECRET=... \
#   REDIS_CONNECTION_STRING=... \
#   ./k8s/stage/generate-stage-secret.sh

NAMESPACE="biatec"
SECRET_NAME="biatec-stage-app-secret"

prompt_if_unset() {
  local var_name="$1"
  local prompt_text="$2"
  local is_secret="${3:-false}"
  if [ -z "${!var_name:-}" ]; then
    if [ "$is_secret" = "true" ]; then
      read -rsp "$prompt_text: " value
      echo
    else
      read -rp "$prompt_text: " value
    fi
    printf -v "$var_name" '%s' "$value"
  fi
}

echo "==> Collecting stage secret values (reuse production's OAuth credentials, or supply your own)"
prompt_if_unset GOOGLE_CLIENT_ID "Google OAuth Client ID"
prompt_if_unset GOOGLE_CLIENT_SECRET "Google OAuth Client Secret" true
prompt_if_unset ENTRA_TENANT_ID "Microsoft Entra Tenant ID (e.g. 'common')"
prompt_if_unset ENTRA_CLIENT_ID "Microsoft Entra Client ID"
prompt_if_unset ENTRA_CLIENT_SECRET "Microsoft Entra Client Secret" true
prompt_if_unset REDIS_CONNECTION_STRING "Redis connection string (fine to reuse production's - see docs/STAGE_ENVIRONMENT.md on the shared-Redis trade-off)" true

echo "==> Generating a fresh AES-256 key/IV dedicated to stage (never reused from production)"
AES_KEY=$(openssl rand -base64 32)
AES_IV=$(openssl rand -base64 16)
AES_KEY_ID="$(date +%Y-%m)-1"

echo "==> Generating a fresh AES-256 key/IV dedicated to stage's provider-access-token caching (BiatecOIDC only, never reused from AesOptions or production)"
PROVIDER_TOKEN_PROTECTION_KEY=$(openssl rand -base64 32)
PROVIDER_TOKEN_PROTECTION_IV=$(openssl rand -base64 16)
PROVIDER_TOKEN_PROTECTION_KEY_ID="$(date +%Y-%m)-1"

echo "==> Generating a fresh 4096-bit RSA signing key dedicated to stage OIDC tokens (never reused from production)"
JWT_SIGNING_KEY=$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096)

# AesOptions/ProviderTokenProtection are rotatable key rings (BiatecSelfCustodyCore.Model.AesOptions /
# BiatecOIDC.Model.ProviderTokenProtectionConfiguration): ActiveKeyId names which entry in Keys[] new
# encryption uses; every entry stays decryptable so already-encrypted data (and already-issued Biatec
# tokens caching a provider token) keeps working until it's naturally re-encrypted/re-issued under the
# active key. This script always creates/replaces the secret with exactly ONE generation - fine for
# first-time setup, but a real *rotation* must ADD a new generation rather than replacing the only one,
# otherwise nothing decryptable under the old key (existing self-custody files, cached provider tokens in
# already-issued tokens) can be read anymore. To rotate:
#   1. Generate a new key/IV pair and a new, never-reused KeyId (e.g. next month's "YYYY-MM-1").
#   2. Re-run `kubectl create secret ... --dry-run=client -o yaml | kubectl apply -f -` yourself with
#      BOTH the new generation (as Keys__0__*) AND every existing generation appended after it
#      (Keys__1__*, Keys__2__*, ...), with ActiveKeyId set to the new generation's KeyId. `kubectl get
#      secret <name> -o json` lets you read back the currently-deployed literals to preserve them.
#   3. `kubectl rollout restart deployment/...` for both deployments (env vars are snapshotted at
#      process start - IOptionsMonitor does not hot-reload a Secret change, so this restart is what
#      actually picks up the rotation; being a rolling restart across replicas, it's zero-downtime).
#   4. Watch logs for "Migrating ... from AES key generation ... to the active generation ..." - once
#      you stop seeing a given old KeyId mentioned (all active users' data has been touched at least
#      once since the rotation), it's safe to drop that generation from Keys[] in a later update.
echo "==> Creating/updating Secret '$SECRET_NAME' in namespace '$NAMESPACE'"
kubectl create secret generic "$SECRET_NAME" \
  --namespace="$NAMESPACE" \
  --from-literal=CloudServices__Google__ClientId="$GOOGLE_CLIENT_ID" \
  --from-literal=CloudServices__Google__ClientSecret="$GOOGLE_CLIENT_SECRET" \
  --from-literal=AesOptions__ActiveKeyId="$AES_KEY_ID" \
  --from-literal=AesOptions__Keys__0__KeyId="$AES_KEY_ID" \
  --from-literal=AesOptions__Keys__0__Key="$AES_KEY" \
  --from-literal=AesOptions__Keys__0__IV="$AES_IV" \
  --from-literal=ProviderTokenProtection__ActiveKeyId="$PROVIDER_TOKEN_PROTECTION_KEY_ID" \
  --from-literal=ProviderTokenProtection__Keys__0__KeyId="$PROVIDER_TOKEN_PROTECTION_KEY_ID" \
  --from-literal=ProviderTokenProtection__Keys__0__Key="$PROVIDER_TOKEN_PROTECTION_KEY" \
  --from-literal=ProviderTokenProtection__Keys__0__IV="$PROVIDER_TOKEN_PROTECTION_IV" \
  --from-literal=CloudServices__Entra__TenantId="$ENTRA_TENANT_ID" \
  --from-literal=CloudServices__Entra__ClientId="$ENTRA_CLIENT_ID" \
  --from-literal=CloudServices__Entra__ClientSecret="$ENTRA_CLIENT_SECRET" \
  --from-literal=Redis__ConnectionString="$REDIS_CONNECTION_STRING" \
  --from-literal=JwtIssuer__SigningPrivateKeyPem="$JWT_SIGNING_KEY" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "✅ Secret '$SECRET_NAME' created/updated in namespace '$NAMESPACE'."
echo "   BiatecMCP ignores the unused JwtIssuer__SigningPrivateKeyPem key - harmless to share the one secret across both stage deployments."
echo "   Restart both stage deployments to pick up any changed values:"
echo "     kubectl rollout restart deployment/biatec-mcp-stage-app-deployment -n $NAMESPACE"
echo "     kubectl rollout restart deployment/biatec-oidc-stage-app-deployment -n $NAMESPACE"
