namespace BiatecMCP.Model
{
    /// <summary>Request to start pairing a device (e.g. an AI assistant) with a Google Drive-backed account.</summary>
    public class DevicePairingRequest
    {
        /// <summary>Unique identifier for the pairing session, generated by the pairing client.</summary>
        public string SessionId { get; set; } = string.Empty;

        /// <summary>Human-readable name of the device being paired, for display purposes.</summary>
        public string DeviceName { get; set; } = string.Empty;
    }

    /// <summary>Result of a device pairing operation (pairing, unpairing, or callback processing).</summary>
    public class DevicePairingResponse
    {
        /// <summary>Whether the operation completed successfully.</summary>
        public bool Success { get; set; }

        /// <summary>Human-readable description of the result, or the error that occurred.</summary>
        public string Message { get; set; } = string.Empty;

        /// <summary>Session ID the operation was performed for.</summary>
        public string? SessionId { get; set; }
    }

    /// <summary>Google OAuth tokens and metadata for a device that has completed pairing.</summary>
    public class PairedDeviceInfo
    {
        /// <summary>Current Google OAuth access token for the paired account.</summary>
        public string AccessToken { get; set; } = string.Empty;

        /// <summary>Google OAuth refresh token, used to obtain new access tokens once this one expires.</summary>
        public string RefreshToken { get; set; } = string.Empty;

        /// <summary>Email address of the Google account the device is paired to.</summary>
        public string Email { get; set; } = string.Empty;

        /// <summary>Human-readable name of the paired device.</summary>
        public string DeviceName { get; set; } = string.Empty;

        /// <summary>When the device completed pairing.</summary>
        public DateTime PairedAt { get; set; }

        /// <summary>When this pairing session expires and must be re-paired.</summary>
        public DateTime ExpiresAt { get; set; }

        /// <summary>
        /// Optional, user-configured allowlist of Algorand receiver addresses the <c>transferAsset</c> MCP tool
        /// is permitted to send to for this session. Empty/unset means unrestricted (the default - no behavior
        /// change unless a user opts in via <c>POST /api/device/receiver-allowlist/{sessionId}</c>).
        /// </summary>
        public List<string> AllowedReceivers { get; set; } = new();
    }
}
